### PR TITLE
Be more careful with calls to .off()

### PR DESCRIPTION
**Pull request by zapper59**
Improve Documentation
Add animation_time as a parameter
Allow .trigger() to trigger custom events
Handle step_data.event correctly when splitting for non-standard events.

### CODE REVIEW

**Comment by darron1217** [comment]
Those are quite huge changes

What do you mean exactly 'Be more careful with calls to .off()' ?

**Comment by zapper59** [comment]
I went to go implement enjoyhint in a project I'm working on, and noticed that when the tour ended all of the window.resize event handlers for my webapp had been removed, breaking the video player on that page.  So more specifically this change makes sure we're using jquery namespaces for all of the event handlers that get set.
https://www.andismith.com/blogs/2013/02/jquery-on-and-off-namespacing/

I realize there's some other big changes I'm trying to merge with this.  Feel free to comment on anything you don't agree with when you can.  I'm just trying to help improve a tool that I think looks useful.

**Comment by darron1217** [comment]
Oh I understood now

I'll test it and then merge it :)
Thanks

**Comment by zapper59** [comment]
I hope you don't mind I've pushed a few more changes.
1) When calling .stop() the hide function wasn't actually being called
2) We should use getBoundingClientRect() all the time. Outer width was causing surrounding text to be included in the size.

**Comment by darron1217** [comment]
Will you create fiddle with page below(including your own script)?
https://darron1217.github.io/enjoyhint.js/docs/index.html

**Comment by zapper59** [comment]
Hi, I've just pushed another commit.  It's a big one and I'm sorry about that, but there's not much substance to it.  I realized earlier today that the existing window resize handler was woefully redundant and inconsistent with the other page drawing logic.  If you actually take a look at your index.html you'll see that if you resize the page and return it to normal the arrow will change orientation.  I've gone ahead and removed the buggy code in favor of using the existing, functional logic.

A working copy of my pull request:
http://zapper59.github.io/enjoyhint/docs/index.html

**Comment by darron1217** [comment]
I agree that this repo was not stable from the beginning

I got no much time to check it all...
I'll trust your passion on this project :)
Thanks for all your work

**Pull request merged**
